#ifndef CONFIG_H
#define CONFIG_H

#define FG			COLOR_WHITE
#define BG			COLOR_GREEN
#define BORDER_FG	COLOR_GREEN
#define BORDER_BG	COLOR_BLACK
#define COUNTER_FG	COLOR_GREEN
#define COUNTER_BG	COLOR_WHITE
#define HELP_FG		COLOR_GREEN
#define HELF_BG		COLOR_WHITE
#define HELF_BG_BG	COLOR_GREEN

#define SCR_A		A_NORMAL
#define BORDER_A	A_BOLD
#define COUNTER_A	A_BOLD
#define HELP_A		A_BOLD

#endif
